### ISSUE TITLE
Cabecera

### ISSUE THREAD

**Issue by fannysm** [Loycus/landing-page#7]
# Ítems de menú
- [x] Poner en tipografía Poppins Medium #8 
- [x] Color blanco a 60% de alpha #8 

### Bloque Ruleta
- [x] Hacer más pequeño el icono de refrescar #9 
- [x] Reducir el margen entre el icono refrescar y la primera caja #10 
- [x] Quitar margen izquierdo a la frase de “cerca de ti” #11 
- [x] Poner "cerca de ti" con tipografía Poppins Semibold #12 
- [x] Aumentar un poco el margen entre las cajas de txt #13 
- [x] Bajar la posición de la malla #14 

-----

- [x] Hacer más grande el logotipo #15 
- [x] Hacer un poco más pequeño el claim "tu red social de compras". _Da la sensación de que tiene reducido el interletrado aunque veo que en código no está_ #16 

![header](https://cloud.githubusercontent.com/assets/28979359/26492345/d2a80140-4213-11e7-8767-2bcfc0375ac3.jpg)

**Comment by fannysm** [comment]
<img width="1240" alt="captura de pantalla 2017-05-26 a las 13 26 27" src="https://cloud.githubusercontent.com/assets/28979359/26492937/10f02d1c-4217-11e7-917b-0d2b4cd75006.png">

**Comment by fannysm** [comment]
El logotipo de Loycus tiene ser más grande
